
security:
  user:
    password: password
  ignored:
    - /css/**
    - /js/**
    - /images/**
    - /**/favicon.ico
    - /webjars/**        

zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:9000
    user:
      path: /user/**
      url: http://localhost:9999/uaa/user

spring:
  oauth2:
    sso:
      home:
        secure: false
        path: /,/**/*.html
    client:
      clientId: acme
      clientSecret: acmesecret
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
    resource:
      userInfoUri: http://localhost:9999/uaa/user

#logging:
#  level:
#    org.springframework.security: DEBUG
#    org.springframework.web: DEBUG
