sudo: false
language: java

jdk:
- oraclejdk8

before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

script:
- ./gradlew ciBuild

after_success:
- bash <(curl -s https://codecov.io/bash)
- ./tools/publish.sh

env:
  global:
    secure: a99QP0V3dkL8UDnzm6+D6uvvMVkNYTK2gG8WbNwoyOCTPkYfJge4Y71zEsxr0drTIo9+G4ADkyzTvDoNzB+8n9x0Q7/545Fgh/RLCnaH4YHqy9piqXTM7nbvKvj9iF2iAYSyJA8qcjNgRVOaqEqgxICq50o64wiClZ5SEegq07C6JrxKM5zClgQVVUREEUWnAkKwGB9wwnGMREv2PeocTx4RKbOyo7OOyKx8/9+jn1tBQmOQy+fo3o8bnMM4A7lqqfZjGqWVLur9iByErJqded/6/610RKBdQYXfE36ReBq3VVfwnNUMlu9LrryFoby4nXYAmN4mwqPW9iUSef+QqkobUlvbNruJVO8GRATQhokMDRw0IsjfHEUa1PziXUsgYIDzbPJQVmeJ/Vh2jARPwPZc1AEG50Dj5Ii7GLoxHpFjjsQb27c36X9MsGI16iQ4VFrG0R8QfDP+Snd+06I43VDA394hK/rkZsRrXP8DHk9TyMJfNKny2I4RiM3lWVincMiwOknu6dtXZMHJFo0vLYLVjkZeXYcmdNbwq8oXKs+1rSP9wfkUn9RM7mkgofU6XNqI+tlVR01jHGoG5Om1hjL8/Guz3ci2/blGRpavgCx98ezFh+PppIoCQ5G3EL+gmJby9idQ6wU+kwMbUu+tPDMwNAVHxUSI1IvoBonMvUg=
