
#
# Common/default settings for all environments
#

spring:
  application:
    name: "OAuth2"
  jpa:
    show-sql: false
    hibernate:
       ddl-auto: none
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 9999
  context-path: /uaa

flyway:
  enabled: true
  init-on-migrate: true
  table: t_schema_version

management:
  context-path: /manage
  security:
    enabled: true
    role: admin

endpoints:
  jolokia:
    sensitive: true
  shutdown:
    enabled: false

---

#
# Settings for development
#

spring:
  profiles: dev
  thymeleaf:
    cache: false
  jpa:
    show-sql: true

---

spring:
  profiles: testdata

flyway:
  locations: classpath:db

---

#
# Settings for test
#

spring:
  profiles: test
  thymeleaf:
    cache: false
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost/test1_hwoauth2
    username: test1
    password: test1
