
#
# Common/default settings for all environments
#

spring:
  application:
    name: "OAuth2"
  jpa:
    show-sql: false
    hibernate:
       ddl-auto: none
#  data:
#    rest:
#      base-uri: /api

server:
  port: 9999
  context-path: /uaa

flyway:
  enabled: true
  init-on-migrate: true
  table: t_schema_version

management:
  security:
    enabled: true
    role: admin

endpoints:
  jolokia:
    sensitive: true
  shutdown:
    enabled: false

---

#
# Settings for development
#

spring:
  profiles: dev
  thymeleaf:
    cache: false
  jpa:
    show-sql: true
#    hibernate:
#       ddl-auto: create-drop
#flyway:
#  enabled: false

#  datasource:
#    driverClassName: org.mariadb.jdbc.Driver
#    url: jdbc:mysql://localhost/dev1_hwoauth2
#    username: dev1
#    password: dev1

---

#
# Settings for test
#

spring:
  profiles: test
  thymeleaf:
    cache: false
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost/test1_hwoauth2
    username: test1
    password: test1

---
